/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/navigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AboutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/BurgerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/cart`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CartScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CheckoutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DessertScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DrinkScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/OrderConfirmationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WrapScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/navigator`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/AboutScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/BurgerScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CartContext`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CartScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CheckoutScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/DessertScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/DrinkScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/OrderConfirmationScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/WrapScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/navigation/navigator${`?${string}` | `#${string}` | ''}` | `/screens/AboutScreen${`?${string}` | `#${string}` | ''}` | `/screens/BurgerScreen${`?${string}` | `#${string}` | ''}` | `/screens/cart${`?${string}` | `#${string}` | ''}` | `/screens/CartContext${`?${string}` | `#${string}` | ''}` | `/screens/CartScreen${`?${string}` | `#${string}` | ''}` | `/screens/CheckoutScreen${`?${string}` | `#${string}` | ''}` | `/screens/DessertScreen${`?${string}` | `#${string}` | ''}` | `/screens/DrinkScreen${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/LoginScreen${`?${string}` | `#${string}` | ''}` | `/screens/OrderConfirmationScreen${`?${string}` | `#${string}` | ''}` | `/screens/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/screens/WrapScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/navigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AboutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/BurgerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/cart`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CartScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CheckoutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DessertScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DrinkScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/OrderConfirmationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WrapScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
